doctrine:
    dbal:
        # 1. GLOBAL SETTINGS (Apply to all connections)
        types:
            datetime: App\Doctrine\Types\UTCDateTimeType
            date: App\Doctrine\Types\UTCDateTimeType
            datetime_immutable: App\Doctrine\Types\UTCDateTimeImmutableType
            date_immutable: App\Doctrine\Types\UTCDateTimeImmutableType
            big_decimal: App\Doctrine\Types\BigDecimalType
            tinyint: App\Doctrine\Types\TinyIntType

        connections:
            default:
                use_savepoints: true
                schema_filter: ~^(?!internal)~
                url: '%env(resolve:DATABASE_URL)%'

            migration_source:
                use_savepoints: true
                schema_filter: ~^(?!internal)~
                url: '%env(resolve:DB_MIGRATION_SOURCE)%'

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true

        entity_managers:
            default: &common_orm_settings
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                identity_generation_preferences:
                    Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    string_functions:
                        regexp: App\Doctrine\Functions\Regexp
                        field: DoctrineExtensions\Query\Mysql\Field
                        field2: App\Doctrine\Functions\Field2
                        natsort: App\Doctrine\Functions\Natsort
                        array_position: App\Doctrine\Functions\ArrayPosition
                        ilike: App\Doctrine\Functions\ILike
                connection: default

            migration_source:
                <<: *common_orm_settings
                connection: migration_source

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod: &prod
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@docker: *prod
